---
- hosts: webservers
  become: yes
  become_user: root
  tasks:
  - name: install git
    package:
     name: git
     state: present
  - name: install java
    package:
     name: openjdk-8-jdk
     state: present
  - name: copy chrome driver
    copy:
     src: /home/ubuntu/chromedriver
     dest: /home/ubuntu
  - name: Install chromium browser
    package:
     name: chromium-browser
     state: present